id: P008113
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG4921
  title: ཏཱ་ར་ནཱ་ཐའི་རང་རྣམ་མ་བཅོས་ལྷུག་པའི་རྟོགས་བརྗོད།
  author: ''
  volumes:
    b11f56a7d51e4c03b984336b313aa8cd:
      image_group_id: I1KG4926
      title: Volume 1 of tāranātha
      volume_number: 1
      total_pages: 666
      base_file: v001.txt
ebook_metadata:
  title: ཏཱ་ར་ནཱ་ཐའི་རང་རྣམ་མ་བཅོས་ལྷུག་པའི་རྟོགས་བརྗོད།
  author: ''
  sku: P008113
  cover: cover.jpg
  layers:
  - pagination
