id: P008113
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG4921
  title: ཏཱ་ར་ནཱ་ཐའི་རང་རྣམ་མ་བཅོས་ལྷུག་པའི་རྟོགས་བརྗོད།
  author: ''
  volumes:
    ff5b2280c80e43c68e57fea270453bb3:
      image_group_id: I1KG4926
      title: ''
      volume_number: 1
      total_pages: 666
ebook_metadata:
  title: ཏཱ་ར་ནཱ་ཐའི་རང་རྣམ་མ་བཅོས་ལྷུག་པའི་རྟོགས་བརྗོད།
  author: ''
  sku: P008113
  cover: cover.jpg
  layers:
  - pagination
