id: I01FFC534
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T22:42:39+00:00'
last_modified: '2022-06-09T04:35:41.749667+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4921
  title: ཏཱ་ར་ནཱ་ཐའི་རང་རྣམ་མ་བཅོས་ལྷུག་པའི་རྟོགས་བརྗོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessRestrictedByTbrc
  restrictedInChina: false
  base:
    9A24:
      image_group_id: I1KG4926
      title: Volume 1 of tāranātha
      total_pages: 666
      order: 1
      base_file: 9A24.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
